spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/multi_tenant_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, info, metrics
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: multi-tenant-saas-core